name: flame_bird
description: A sample Flappy Bird clone using Flame.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flame: 0.17.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false

  assets:
   - assets/images/bird.png
